#!/usr/bin/env bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

sync_repo(){
  repo_list=(freenom lede helloworld v2ray-core naiveproxy Xray-core)
  owner_list=(luolongfei coolsnowwolf fw876 v2fly klzgrad XTLS)
  for i in `seq 0 $((${#repo_list[@]}-1))`
    do
      [[ ! -d ${repo_list[i]} ]] && git clone git@github.com:lazymartin/${repo_list[i]}.git
      cd ${repo_list[i]}/
      BRANCHNAME=`git checkout|awk -F "/" '{print $2}'|sed "s/'.//g"`
      upstream_name=`git remote -v|grep ${owner_list[i]}/${repo_list[i]}`
      [[ -z ${upstream_name} ]] && git remote add upstream git@github.com:${owner_list[i]}/${repo_list[i]}.git
      git pull upstream ${BRANCHNAME}
      git push origin
      if [[ $? -eq 0 ]];then logger "${repo_list[i]} has synchronized with upstream!";else logger "==ERROR== ${repo_list[i]} failed to synchronize with upstream!";fi
    cd ${HOME}/github
    done
}

mkdir -p ${HOME}/github
cd ${HOME}/github
sync_repo
cd
