#!/usr/bin/env bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

update_app(){
  systemctl stop nginx &>/dev/null
  systemctl stop xray &>/dev/null
  ps -aux|grep -v grep|grep -Ei "nginx|xray"|awk -F " " '{print $2}'|xargs kill -9 &>/dev/null
  apt install -y nginx
  if [[ $? -eq 0 ]];then logger "Nginx upgrade succeeded!";else logger "Nginx upgrade failed!";fi
  /root/.acme.sh/acme.sh --upgrade &>/dev/null
  if [[ $? -eq 0 ]];then logger "acme upgrade succeeded!";else logger "acme upgrade failed!";fi
  bash <(curl -Ls https://raw.githubusercontent.com/lazymartin/scripts/master/install_xray.sh)
  if [[ $? -eq 0 ]];then logger "Xray-core upgrade succeeded!";else logger "Xray-core upgrade failed!";fi
  systemctl daemon-reload &>/dev/null
  systemctl start nginx &>/dev/null
  systemctl start xray &>/dev/null
}

del_log(){
  rm -rf /var/log/{auth.log.*,syslog.*,user.*,dpkg.log.*,kern.log.*,messages.*,daemon.log.*,debug.*,fail2ban.log.*,alternatives.log.*,mail.err.*,mail.info.*,mail.log.*,mail.warn.*,btmp.*,wtmp.*}
  rm -rf /var/log/nginx/{access.log.*,error.log.*}
  echo "" > /var/log/xray/access.log
  echo "" > /var/log/xray/error.log
  logger "The specified log file has been emptied."
}

update_freenom(){
  cd ~/freenom
  BRANCHNAME=`git checkout|awk -F "/" '{print $2}'|sed "s/'.//g"`
  # latest_commit=`curl -s https://github.com/luolongfei/freenom/commits/master|grep "data-url"|awk -F "/" 'NR==1 {print $5}'`
  rollback_commit="f9218406445dd5d7bb29c7562ef720d08fea3a92"
  git reset --hard ${rollback_commit}
  git push origin ${BRANCHNAME} --force
  sleep 60
  git pull upstream ${BRANCHNAME}
  git push origin ${BRANCHNAME}
  logger "Repository of freenom Active status has been updated!"
  cd ~
}

update_freenom_old(){
  cd ~/freenom
  if [[ -s check.md ]]; then
      cat /dev/null > check.md
    else
      echo "check update" > check.md
  fi
  git add -A && git commit -a -m "push" && git push
  logger "Repository of freenom Active status has been updated!"
  cd ~
}

update_app
del_log
update_freenom
