# 监听端口
listen-ports:
  - 53

# 监听地址
listen-addrs:
  - "127.0.0.1"
  - "::1"

# 上游 DNS 服务器列表
upstream:
  # 指定 netflix 域名使用的上游
  - "[/fast.com/]${netflix_dns}"
  - "[/netflix.ca/]${netflix_dns}"
  - "[/netflix.com/]${netflix_dns}"
  - "[/netflix.com.edgesuite.net/]${netflix_dns}"
  - "[/netflix.net/]${netflix_dns}"
  - "[/netflixdnstest0.com/]${netflix_dns}"
  - "[/netflixdnstest1.com/]${netflix_dns}"
  - "[/netflixdnstest10.com/]${netflix_dns}"
  - "[/netflixdnstest2.com/]${netflix_dns}"
  - "[/netflixdnstest3.com/]${netflix_dns}"
  - "[/netflixdnstest4.com/]${netflix_dns}"
  - "[/netflixdnstest5.com/]${netflix_dns}"
  - "[/netflixdnstest6.com/]${netflix_dns}"
  - "[/netflixdnstest7.com/]${netflix_dns}"
  - "[/netflixdnstest8.com/]${netflix_dns}"
  - "[/netflixdnstest9.com/]${netflix_dns}"
  - "[/netflixinvestor.com/]${netflix_dns}"
  - "[/netflixtechblog.com/]${netflix_dns}"
  - "[/nflxext.com/]${netflix_dns}"
  - "[/nflximg.com/]${netflix_dns}"
  - "[/nflximg.net/]${netflix_dns}"
  - "[/nflxsearch.net/]${netflix_dns}"
  - "[/nflxso.net/]${netflix_dns}"
  - "[/nflxvideo.net/]${netflix_dns}"
  # 解析 ${mirror_name} 镜像地址
  - "[/${mirror_site}/]${mirror_site_dns}"
  # 指定 ${domain} 及其子域名使用的上游
  - "[/*.${domain}/]tls://1.1.1.1"
  # 默认上游：Cloudflare DNS over TLS
  - "tls://1.1.1.1"

# 缓存设置
cache: true
cache-size: 33554432        # 缓存大小，可根据内存情况调整
cache-min-ttl: 0        # 最小 TTL，设为 0 以完全尊重上游返回的 TTL（对不缓存域名很重要）
cache-max-ttl: 3600     # 最大 TTL，防止过时记录缓存太久
cache-optimistic: false # 关闭乐观缓存，防止返回过期数据（对实时性要求高的域名很重要）

# 其他优化
ratelimit: 0            # 速率限制 (0 表示禁用，仅本地使用通常不需要限制)
verbose: false          # 日志详细程度
insecure: false         # 验证上游 TLS 证书 (设为 false 保证安全)
ipv6-disabled: false    # 启用内部 IPv6 解析支持
