#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: GPL-3.0
# Author: lazymartin
#=================================================

name: Compile aria2 linux x86_64 Latest release

on:
  schedule:
    - cron: '10 00 * * 0'
  push:
    paths: 
      - '.github/workflows/compile_aria2_linux_x86_64_64-threads.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        
    - name: Install dependences
      run: |
        
        #COMPILER AND PATH
        PREFIX=/opt/aria2/build_libs
        C_COMPILER="gcc"
        CXX_COMPILER="g++"
        
        #CHECK TOOL FOR DOWNLOAD
         aria2c --help > /dev/null
         if [ "$?" -eq 0 ] ; then
           DOWNLOADER="aria2c --check-certificate=false"
         else
           DOWNLOADER="wget -c"
         fi
        
        ## DEPENDENCES ##
        ZLIB=http://sourceforge.net/projects/libpng/files/zlib/1.2.11/zlib-1.2.11.tar.gz
        OPENSSL=http://www.openssl.org/source/openssl-1.0.2u.tar.gz
        EXPAT=https://github.com/libexpat/libexpat/releases/download/R_2_2_10/expat-2.2.10.tar.bz2
        SQLITE3=https://sqlite.org/2020/sqlite-autoconf-3330000.tar.gz
        C_ARES=https://c-ares.haxx.se/download/c-ares-1.16.1.tar.gz
        SSH2=https://www.libssh2.org/download/libssh2-1.7.0.tar.gz
        
        ## CONFIG ##
        BUILD_DIRECTORY=/tmp/
        
        ## BUILD ##
        cd $BUILD_DIRECTORY
        #
         # zlib build
          $DOWNLOADER $ZLIB
          tar zxvf zlib-1.2.11.tar.gz
          cd zlib-1.2.11/
          PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./configure --prefix=$PREFIX --static
          make -j$(nproc)
          make install
        #
         # expat build
          cd ..
          $DOWNLOADER $EXPAT
          tar jxvf expat-2.2.10.tar.bz2
          cd expat-2.2.10/
          PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./configure --prefix=$PREFIX --enable-static --enable-shared
          make -j$(nproc)
          make install
        #
         # c-ares build
          cd ..
          $DOWNLOADER $C_ARES
          tar zxvf c-ares-1.16.1.tar.gz
          cd c-ares-1.16.1/
          PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./configure --prefix=$PREFIX --enable-static --disable-shared
          make -j$(nproc)
          make install
        #
         # Openssl build
          cd ..
          $DOWNLOADER $OPENSSL
          tar zxvf openssl-1.0.2u.tar.gz
          cd openssl-1.0.2u/
          PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./Configure --prefix=$PREFIX linux-x86_64 shared
          make -j$(nproc)
          make install
        #
         # sqlite3
          cd ..
          $DOWNLOADER $SQLITE3
          tar zxvf sqlite-autoconf-3330000.tar.gz
          cd sqlite-autoconf-3330000/
          PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./configure --prefix=$PREFIX --enable-static --enable-shared
          make -j$(nproc)
          make install
        #
         # libssh2
          cd ..
          $DOWNLOADER $SSH2
          tar zxvf libssh2-1.7.0.tar.gz
          cd libssh2-1.7.0/
          rm -rf $PREFIX/lib/pkgconfig/libssh2.pc
          PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./configure --without-libgcrypt --with-openssl --without-wincng --prefix=$PREFIX --enable-static --disable-shared
          make -j$(nproc)
          make install
        #
    - name: Compile
      run: |
        REPO_NAME="aria2/aria2"
        FILE_VER=`curl -s https://api.github.com/repos/$REPO_NAME/releases/latest|grep tag_name|awk -F "\"" '{print $4}'|grep -oE [0-9].[0-9]*.[0-9]*`
        FILE_NAME=`curl -s https://api.github.com/repos/$REPO_NAME/releases/latest|grep $FILE_VER.tar.xz|awk -F "\"" 'NR==1 {print $4}'`
        DOWNLOAD_LINK=`curl -s https://api.github.com/repos/$REPO_NAME/releases/latest|grep -oE "https://github.com.*$FILE_VER.tar.xz"`
        
        wget -q $DOWNLOAD_LINK --show-progress -O $FILE_NAME
        tar xf $FILE_NAME
        cd `echo $FILE_NAME|sed "s/.tar.xz//g"`
        sed -i s"/1\, 16\,/1\, 64\,/" ./src/OptionHandlerFactory.cc
        
        #COMPILER AND PATH
        PREFIX=/usr/sbin
        C_COMPILER="gcc"
        CXX_COMPILER="g++"
        
        ## BUILD ##
        PKG_CONFIG_PATH=/opt/aria2/build_libs/lib/pkgconfig/ \
        LD_LIBRARY_PATH=/opt/aria2/build_libs/lib/ \
        CC="$C_COMPILER" \
        CXX="$CXX_COMPILER" \
        ./configure \
            --prefix=$PREFIX \
            --without-libxml2 \
            --without-libgcrypt \
            --with-openssl \
            --without-libnettle \
            --without-gnutls \
            --without-libgmp \
            --with-libssh2 \
            --with-sqlite3 \
            --with-ca-bundle='/etc/ssl/certs/ca-certificates.crt' \
            ARIA2_STATIC=yes \
            --enable-shared=no
        make -j$(nproc)
        strip -s ./src/aria2c

    - name: Assemble Artifact
      run: |
        mkdir -p ./artifact
        REPO_NAME="aria2/aria2"
        FILE_VER=`curl -s https://api.github.com/repos/$REPO_NAME/releases/latest|grep tag_name|awk -F "\"" '{print $4}'|grep -oE [0-9].[0-9]*.[0-9]*`
        work_path=`curl -s https://api.github.com/repos/$REPO_NAME/releases/latest|grep $FILE_VER.tar.xz|awk -F "\"" 'NR==1 {print $4}'|sed "s/.tar.xz//g"`
        cp /home/runner/work/scripts/scripts/${work_path}/src/aria2c ./artifact/aria2c_linux_x86_64_64-threads
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./artifact/*
        tag: "Last_release"
        overwrite: true
        file_glob: true
 
