#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: GPL-3.0
# Author: lazymartin
#=================================================

name: Compile aria2 windows x86_64 Latest release

env:
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  TZ: Asia/Shanghai

on:
  schedule:
    - cron: '00 19 * * 0'
  push:
    paths: 
      - '.github/workflows/compile_aria2_windows_x86_64_64-threads.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
        
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
        
    - name: Install dependences
      id: dependences
      continue-on-error: true
      run: |
        
        # IMPORTANT: Require install gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
        # CHECK TOOL FOR DOWNLOAD
        DOWNLOADER="wget -c"
        
        ## DEPENDENCES ##
        ZLIB=http://sourceforge.net/projects/libpng/files/zlib/1.2.11/zlib-1.2.11.tar.gz
        OPENSSL=http://www.openssl.org/source/openssl-1.0.2u.tar.gz
        EXPAT=https://github.com/libexpat/libexpat/releases/download/R_2_2_10/expat-2.2.10.tar.bz2
        SQLITE3=https://sqlite.org/2020/sqlite-autoconf-3330000.tar.gz
        C_ARES=https://c-ares.haxx.se/download/c-ares-1.16.1.tar.gz
        SSH2=https://www.libssh2.org/download/libssh2-1.7.0.tar.gz

        ## CONFIG ##
        BUILD_DIRECTORY=/tmp/
        HOST=x86_64-w64-mingw32
        PREFIX=/usr/x86_64-w64-mingw32

        ## BUILD ##
        cd $BUILD_DIRECTORY
        #
         # zlib build
          $DOWNLOADER $ZLIB
          tar zxvf zlib-1.2.11.tar.gz
          cd zlib-1.2.11/
          CC=$HOST-gcc CXX=$HOST-g++ AR=$HOST-ar RANLIB=$HOST-ranlib ./configure --prefix=$PREFIX --static
          sudo make
          sudo make install
        #
         # expat build
          cd ..
          $DOWNLOADER $EXPAT
          tar jxvf expat-2.2.10.tar.bz2
          cd expat-2.2.10/
          CC=$HOST-gcc CXX=$HOST-g++ AR=$HOST-ar RANLIB=$HOST-ranlib ./configure --prefix=$PREFIX --host=$HOST --enable-static --enable-shared
          sudo make
          sudo make install
        #
         # c-ares build
          cd ..
          $DOWNLOADER $C_ARES
          tar zxvf c-ares-1.16.1.tar.gz
          cd c-ares-1.16.1/
          CC=$HOST-gcc CXX=$HOST-g++ AR=$HOST-ar RANLIB=$HOST-ranlib ./configure --prefix=$PREFIX --host=$HOST --enable-static --disable-shared
          sudo make
          sudo make install
        #
         # Openssl build
          cd ..
          $DOWNLOADER $OPENSSL
          tar zxvf openssl-1.0.2u.tar.gz
          cd openssl-1.0.2u/
          ./Configure mingw64 --cross-compile-prefix=$HOST- --prefix=$PREFIX shared
          sudo make
          sudo make install
        #
         # sqlite3
          cd ..
          $DOWNLOADER $SQLITE3
          tar zxvf sqlite-autoconf-3330000.tar.gz
          cd sqlite-autoconf-3330000/
          CC=$HOST-gcc CXX=$HOST-g++ AR=$HOST-ar RANLIB=$HOST-ranlib ./configure --prefix=$PREFIX --host=$HOST --enable-static --enable-shared
          sudo make
          sudo make install
        #
         # libssh2
          cd ..
          $DOWNLOADER $SSH2
          tar zxvf libssh2-1.7.0.tar.gz
          cd libssh2-1.7.0/
          rm -rf $PREFIX/lib/pkgconfig/libssh2.pc
          CC=$HOST-gcc CXX=$HOST-g++ AR=$HOST-ar RANLIB=$HOST-ranlib ./configure --prefix=$PREFIX --host=$HOST --enable-static --disable-shared
          sudo make
          sudo make install
          
    - name: Check dependency installation
      # if: steps.dependences.outcome != 'success' || steps.compile.outcome != 'success'
      if: steps.dependences.outcome != 'success'
      run: |
        curl -s --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=Failed to install aria2 windows_x86_x64 dependency, compilation terminated!!" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
        
    - name: Compile
      id: compile
      continue-on-error: true
      run: |
        REPO_NAME="aria2/aria2"
        FILE_VER=`curl -s --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$REPO_NAME/releases/latest|grep tag_name|awk -F "\"" '{print $4}'|grep -oE "([0-9]{1,2}\.){2}[0-9]{1,2}"`
        FILE_NAME=`curl -s --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$REPO_NAME/releases/latest|grep $FILE_VER.tar.xz|awk -F "\"" 'NR==1 {print $4}'`
        DOWNLOAD_LINK=`curl -s --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$REPO_NAME/releases/latest|grep -oE "https://github.com.*$FILE_VER.tar.xz"`
        
        wget -q $DOWNLOAD_LINK --show-progress -O $FILE_NAME
        tar xf $FILE_NAME
        cd `echo $FILE_NAME|sed "s/.tar.xz//g"`
        sed -i s"/\"1\"\, 1\, 16\, \'x\'/\"1\"\, 1\, 64\, \'x\'/g" ./src/OptionHandlerFactory.cc
        sed -i s"/1\, 16\,/1\, 64\,/g" ./src/OptionHandlerFactory.cc
        
        HOST=x86_64-w64-mingw32
        PREFIX=/usr/x86_64-w64-mingw32

        ./configure \
            --host=$HOST \
            --prefix=$PREFIX \
            --without-included-gettext \
            --disable-nls \
            --with-libcares \
            --without-gnutls \
            --without-wintls \
            --with-openssl \
            --with-sqlite3 \
            --without-libxml2 \
            --with-libexpat \
            --with-libz \
            --without-libgmp \
            --with-libssh2 \
            --without-libgcrypt \
            --without-libnettle \
            --with-cppunit-prefix=$PREFIX \
            ARIA2_STATIC=yes \
            CPPFLAGS="-I$PREFIX/include" \
            LDFLAGS="-L$PREFIX/lib" \
            PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig"
        sudo make
        
    - name: Check compilation
      if: steps.compile.outcome != 'success'
      run: |
        curl -s --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=Compiling aria2 windows_x86_x64 failed!!" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
    - name: Assemble Artifact
      run: |
        mkdir -p ./artifact
        REPO_NAME="aria2/aria2"
        FILE_VER=`curl -s --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$REPO_NAME/releases/latest|grep tag_name|awk -F "\"" '{print $4}'|grep -oE "([0-9]{1,2}\.){2}[0-9]{1,2}"`
        work_path=`curl -s --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$REPO_NAME/releases/latest|grep $FILE_VER.tar.xz|awk -F "\"" 'NR==1 {print $4}'|sed "s/.tar.xz//g"`
        cp /home/runner/work/scripts/scripts/${work_path}/src/aria2c.exe ./artifact/aria2c_windows_x86_64_64-threads.exe
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./artifact/*
        tag: "Last_release"
        overwrite: true
        file_glob: true
