#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: GPL-3.0
# Author: lazymartin
#=================================================

name: Compile aria2 macOS Latest release

env:
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  shell: bash
  TZ: Asia/Shanghai

on:
  schedule:
    - cron: '00 19 * * 0'
  push:
    paths: 
      - '.github/workflows/test.yml'
    
jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: run test
      id: test
      run: |
        wget https://github.com/lazymartin/scripts/releases/download/Last_release/aria2c_macOS_64-threads
        chmod +x aria2c_macOS_64-threads
        ./aria2c_macOS_64-threads -v
        ./aria2c_macOS_64-threads -h